name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Docker Build
      uses: docker/setup-buildx-action@v2.0.0
    
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: omateusvalente
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
    
    - name: Build and Push Docker Images
      user: docker/build-push-actions@v3.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: omateusvalente/go_ci:${{github.ref_name}}
